export interface MidiLibraryItem {
  categoryId: string
  categoryLabel: string
  durationLabel: string
  fileName: string
  id: string
  sourceUrl?: string
  subtitle: string
  title: string
  url: string
}

export interface MidiLibraryCategory {
  id: string
  label: string
  items: MidiLibraryItem[]
}

export const MIDI_LIBRARY_CATEGORIES: MidiLibraryCategory[] = [
  {
    id: 'originals',
    items: [
      {
        categoryId: 'originals',
        categoryLabel: 'Originals',
        durationLabel: '1:41',
        fileName: 'miras-theme.mid',
        id: 'originals/miras-theme',
        subtitle: 'itsjaydesu',
        title: 'Mira\'s Theme',
        url: '/midi/originals/miras-theme.mid',
      },
    ],
    label: 'Originals',
  },
  {
    id: 'classical-piano',
    items: [
      {
        categoryId: 'classical-piano',
        categoryLabel: 'Classical & Piano',
        durationLabel: '5:47',
        fileName: 'beethoven-moonlight-sonata.mid',
        id: 'classical-piano/beethoven-moonlight-sonata',
        subtitle: 'Ludwig van Beethoven',
        title: 'Moonlight Sonata',
        url: '/midi/classical-piano/beethoven-moonlight-sonata.mid',
      },
      {
        categoryId: 'classical-piano',
        categoryLabel: 'Classical & Piano',
        durationLabel: '6:56',
        fileName: 'mozart-piano-concerto-no-21-elvira-madigan.mid',
        id: 'classical-piano/mozart-piano-concerto-no-21-elvira-madigan',
        subtitle: 'Wolfgang Amadeus Mozart',
        title: 'Piano Concerto No. 21 (Elvira Madigan)',
        url: '/midi/classical-piano/mozart-piano-concerto-no-21-elvira-madigan.mid',
      },
      {
        categoryId: 'classical-piano',
        categoryLabel: 'Classical & Piano',
        durationLabel: '2:26',
        fileName: 'bach-prelude-from-cello-suite.mid',
        id: 'classical-piano/bach-prelude-from-cello-suite',
        subtitle: 'Johann Sebastian Bach',
        title: 'Prelude from Cello Suite',
        url: '/midi/classical-piano/bach-prelude-from-cello-suite.mid',
      },
      {
        categoryId: 'classical-piano',
        categoryLabel: 'Classical & Piano',
        durationLabel: '3:04',
        fileName: 'yiruma-river-flows-in-you.mid',
        id: 'classical-piano/yiruma-river-flows-in-you',
        subtitle: 'Yiruma',
        title: 'River Flows in You',
        url: '/midi/classical-piano/yiruma-river-flows-in-you.mid',
      },
      {
        categoryId: 'classical-piano',
        categoryLabel: 'Classical & Piano',
        durationLabel: '3:32',
        fileName: 'tchaikovsky-swan-lake.mid',
        id: 'classical-piano/tchaikovsky-swan-lake',
        subtitle: 'Pyotr Ilyich Tchaikovsky',
        title: 'Swan Lake',
        url: '/midi/classical-piano/tchaikovsky-swan-lake.mid',
      },
    ],
    label: 'Classical & Piano',
  },
  {
    id: 'film-tv-anime',
    items: [
      {
        categoryId: 'film-tv-anime',
        categoryLabel: 'Film, TV & Anime',
        durationLabel: '4:03',
        fileName: 'evangelion-cruel-angels-thesis.mid',
        id: 'film-tv-anime/evangelion-cruel-angels-thesis',
        subtitle: 'Yoko Takahashi',
        title: 'Cruel Angel\'s Thesis',
        url: '/midi/film-tv-anime/evangelion-cruel-angels-thesis.mid',
      },
      {
        categoryId: 'film-tv-anime',
        categoryLabel: 'Film, TV & Anime',
        durationLabel: '1:46',
        fileName: 'star-wars-imperial-march.mid',
        id: 'film-tv-anime/star-wars-imperial-march',
        subtitle: 'John Williams',
        title: 'Imperial March',
        url: '/midi/film-tv-anime/star-wars-imperial-march.mid',
      },
      {
        categoryId: 'film-tv-anime',
        categoryLabel: 'Film, TV & Anime',
        durationLabel: '3:12',
        fileName: 'nuovo-cinema-paradiso.mid',
        id: 'film-tv-anime/nuovo-cinema-paradiso',
        subtitle: 'Ennio Morricone',
        title: 'Nuovo Cinema Paradiso',
        url: '/midi/film-tv-anime/nuovo-cinema-paradiso.mid',
      },
      {
        categoryId: 'film-tv-anime',
        categoryLabel: 'Film, TV & Anime',
        durationLabel: '1:35',
        fileName: 'star-wars-theme.mid',
        id: 'film-tv-anime/star-wars-theme',
        subtitle: 'John Williams',
        title: 'Star Wars Theme',
        url: '/midi/film-tv-anime/star-wars-theme.mid',
      },
      {
        categoryId: 'film-tv-anime',
        categoryLabel: 'Film, TV & Anime',
        durationLabel: '1:28',
        fileName: 'succession-theme.mid',
        id: 'film-tv-anime/succession-theme',
        subtitle: 'Nicholas Britell',
        title: 'Succession Theme',
        url: '/midi/film-tv-anime/succession-theme.mid',
      },
      {
        categoryId: 'film-tv-anime',
        categoryLabel: 'Film, TV & Anime',
        durationLabel: '1:27',
        fileName: 'the-simpsons-theme.mid',
        id: 'film-tv-anime/the-simpsons-theme',
        subtitle: 'Danny Elfman',
        title: 'The Simpsons Theme',
        url: '/midi/film-tv-anime/the-simpsons-theme.mid',
      },
    ],
    label: 'Film, TV & Anime',
  },
  {
    id: 'games-internet',
    items: [
      {
        categoryId: 'games-internet',
        categoryLabel: 'Games & Internet',
        durationLabel: '1:16',
        fileName: 'bubble-bobble.mid',
        id: 'games-internet/bubble-bobble',
        subtitle: 'Taito',
        title: 'Bubble Bobble',
        url: '/midi/games-internet/bubble-bobble.mid',
      },
      {
        categoryId: 'games-internet',
        categoryLabel: 'Games & Internet',
        durationLabel: '1:11',
        fileName: 'chrono-trigger-main-theme.mid',
        id: 'games-internet/chrono-trigger-main-theme',
        subtitle: 'Yasunori Mitsuda',
        title: 'Chrono Trigger Main Theme',
        url: '/midi/games-internet/chrono-trigger-main-theme.mid',
      },
      {
        categoryId: 'games-internet',
        categoryLabel: 'Games & Internet',
        durationLabel: '1:24',
        fileName: 'ducktales-moon-theme.mid',
        id: 'games-internet/ducktales-moon-theme',
        subtitle: 'DuckTales',
        title: 'DuckTales Moon Theme',
        url: '/midi/games-internet/ducktales-moon-theme.mid',
      },
      {
        categoryId: 'games-internet',
        categoryLabel: 'Games & Internet',
        durationLabel: '1:40',
        fileName: 'mii-channel-theme.mid',
        id: 'games-internet/mii-channel-theme',
        subtitle: 'Nintendo Wii',
        title: 'Mii Channel Theme',
        url: '/midi/games-internet/mii-channel-theme.mid',
      },
      {
        categoryId: 'games-internet',
        categoryLabel: 'Games & Internet',
        durationLabel: '1:53',
        fileName: 'nyan-cat.mid',
        id: 'games-internet/nyan-cat',
        subtitle: 'Internet Classic',
        title: 'Nyan Cat',
        url: '/midi/games-internet/nyan-cat.mid',
      },
      {
        categoryId: 'games-internet',
        categoryLabel: 'Games & Internet',
        durationLabel: '2:55',
        fileName: 'portal-still-alive.mid',
        id: 'games-internet/portal-still-alive',
        subtitle: 'Portal / Jonathan Coulton',
        title: 'Still Alive',
        url: '/midi/games-internet/portal-still-alive.mid',
      },
      {
        categoryId: 'games-internet',
        categoryLabel: 'Games & Internet',
        durationLabel: '3:28',
        fileName: 'subwoofer-lullaby.mid',
        id: 'games-internet/subwoofer-lullaby',
        subtitle: 'C418 / Minecraft',
        title: 'Subwoofer Lullaby',
        url: '/midi/games-internet/subwoofer-lullaby.mid',
      },
      {
        categoryId: 'games-internet',
        categoryLabel: 'Games & Internet',
        durationLabel: '0:44',
        fileName: 'sweden.mid',
        id: 'games-internet/sweden',
        subtitle: 'C418 / Minecraft',
        title: 'Sweden',
        url: '/midi/games-internet/sweden.mid',
      },
      {
        categoryId: 'games-internet',
        categoryLabel: 'Games & Internet',
        durationLabel: '0:34',
        fileName: 'tetris-main-theme.mid',
        id: 'games-internet/tetris-main-theme',
        subtitle: 'Tetris',
        title: 'Tetris Main Theme',
        url: '/midi/games-internet/tetris-main-theme.mid',
      },
      {
        categoryId: 'games-internet',
        categoryLabel: 'Games & Internet',
        durationLabel: '3:28',
        fileName: 'theme-song-to-2008.mid',
        id: 'games-internet/theme-song-to-2008',
        subtitle: 'you\'ll know the artist',
        title: 'Theme Song to 2008',
        url: '/midi/games-internet/theme-song-to-2008.mid',
      },
    ],
    label: 'Games & Internet',
  },
  {
    id: 'pop-electronic',
    items: [
      {
        categoryId: 'pop-electronic',
        categoryLabel: 'Pop & Electronic',
        durationLabel: '5:10',
        fileName: 'coldplay-a-sky-full-of-stars.mid',
        id: 'pop-electronic/coldplay-a-sky-full-of-stars',
        subtitle: 'Coldplay',
        title: 'A Sky Full of Stars',
        url: '/midi/pop-electronic/coldplay-a-sky-full-of-stars.mid',
      },
      {
        categoryId: 'pop-electronic',
        categoryLabel: 'Pop & Electronic',
        durationLabel: '3:48',
        fileName: 'fireflies.mid',
        id: 'pop-electronic/fireflies',
        subtitle: 'Owl City',
        title: 'Fireflies',
        url: '/midi/pop-electronic/fireflies.mid',
      },
      {
        categoryId: 'pop-electronic',
        categoryLabel: 'Pop & Electronic',
        durationLabel: '0:14',
        fileName: 'kernkraft-400.mid',
        id: 'pop-electronic/kernkraft-400',
        subtitle: 'Zombie Nation',
        title: 'Kernkraft 400',
        url: '/midi/pop-electronic/kernkraft-400.mid',
      },
      {
        categoryId: 'pop-electronic',
        categoryLabel: 'Pop & Electronic',
        durationLabel: '5:49',
        fileName: 'piano-man.mid',
        id: 'pop-electronic/piano-man',
        subtitle: 'Billy Joel',
        title: 'Piano Man',
        url: '/midi/pop-electronic/piano-man.mid',
      },
      {
        categoryId: 'pop-electronic',
        categoryLabel: 'Pop & Electronic',
        durationLabel: '2:07',
        fileName: 'yesterday.mid',
        id: 'pop-electronic/yesterday',
        subtitle: 'The Beatles',
        title: 'Yesterday',
        url: '/midi/pop-electronic/yesterday.mid',
      },
    ],
    label: 'Pop & Electronic',
  },
  {
    id: 'train-stations',
    items: [
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:10',
        fileName: 'akihabara-jr-sh2.mid',
        id: 'train-stations/akihabara-jr-sh2',
        subtitle: 'Tokyo Area Station',
        title: 'Akihabara JR-SH2',
        url: '/midi/train-stations/akihabara-jr-sh2.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:16',
        fileName: 'ebisu.mid',
        id: 'train-stations/ebisu',
        subtitle: 'Yamanote Line Station',
        title: 'Ebisu',
        url: '/midi/train-stations/ebisu.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:13',
        fileName: 'ebisu-third-man-theme.mid',
        id: 'train-stations/ebisu-third-man-theme',
        subtitle: 'Yamanote Line Station',
        title: 'Ebisu Third Man Theme',
        url: '/midi/train-stations/ebisu-third-man-theme.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:13',
        fileName: 'harajuku.mid',
        id: 'train-stations/harajuku',
        subtitle: 'Yamanote Line Station',
        title: 'Harajuku',
        url: '/midi/train-stations/harajuku.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:10',
        fileName: 'ikebukuro-platform-7-teichiku.mid',
        id: 'train-stations/ikebukuro-platform-7-teichiku',
        subtitle: 'Yamanote Line Station',
        title: 'Ikebukuro Platform 7 Teichiku',
        url: '/midi/train-stations/ikebukuro-platform-7-teichiku.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:16',
        fileName: 'kaihin-makuhari-melody.mid',
        id: 'train-stations/kaihin-makuhari-melody',
        subtitle: 'Tokyo Area Station',
        title: 'Kaihin Makuhari Melody',
        url: '/midi/train-stations/kaihin-makuhari-melody.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:11',
        fileName: 'kamata.mid',
        id: 'train-stations/kamata',
        subtitle: 'Tokyo Area Station',
        title: 'Kamata',
        url: '/midi/train-stations/kamata.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:18',
        fileName: 'kawagoe-melody.mid',
        id: 'train-stations/kawagoe-melody',
        subtitle: 'Tokyo Area Station',
        title: 'Kawagoe Melody',
        url: '/midi/train-stations/kawagoe-melody.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:13',
        fileName: 'kitasenju.mid',
        id: 'train-stations/kitasenju',
        subtitle: 'Tokyo Area Station',
        title: 'Kitasenju',
        url: '/midi/train-stations/kitasenju.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:13',
        fileName: 'koenji-awa-odori.mid',
        id: 'train-stations/koenji-awa-odori',
        subtitle: 'Yamanote Line Station',
        title: 'Koenji Awa Odori',
        url: '/midi/train-stations/koenji-awa-odori.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:19',
        fileName: 'komagome.mid',
        id: 'train-stations/komagome',
        subtitle: 'Yamanote Line Station',
        title: 'Komagome',
        url: '/midi/train-stations/komagome.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:19',
        fileName: 'komagome-sakura-sakura.mid',
        id: 'train-stations/komagome-sakura-sakura',
        subtitle: 'Yamanote Line Station',
        title: 'Komagome Sakura Sakura',
        url: '/midi/train-stations/komagome-sakura-sakura.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:12',
        fileName: 'maihama-disney.mid',
        id: 'train-stations/maihama-disney',
        subtitle: 'Tokyo Area Station',
        title: 'Maihama Disney',
        url: '/midi/train-stations/maihama-disney.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:11',
        fileName: 'matsudo.mid',
        id: 'train-stations/matsudo',
        subtitle: 'Tokyo Area Station',
        title: 'Matsudo',
        url: '/midi/train-stations/matsudo.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:17',
        fileName: 'niiza-astro-boy.mid',
        id: 'train-stations/niiza-astro-boy',
        subtitle: 'Tokyo Area Station',
        title: 'Niiza Astro Boy',
        url: '/midi/train-stations/niiza-astro-boy.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:10',
        fileName: 'okutama-donguri-korokoro.mid',
        id: 'train-stations/okutama-donguri-korokoro',
        subtitle: 'Tokyo Area Station',
        title: 'Okutama Donguri Korokoro',
        url: '/midi/train-stations/okutama-donguri-korokoro.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:12',
        fileName: 'ome-akko-chan-theme.mid',
        id: 'train-stations/ome-akko-chan-theme',
        subtitle: 'Tokyo Area Station',
        title: 'Ome Akko Chan Theme',
        url: '/midi/train-stations/ome-akko-chan-theme.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:11',
        fileName: 'osaki.mid',
        id: 'train-stations/osaki',
        subtitle: 'Yamanote Line Station',
        title: 'Osaki',
        url: '/midi/train-stations/osaki.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:09',
        fileName: 'shibuya-platform-1-teichiku.mid',
        id: 'train-stations/shibuya-platform-1-teichiku',
        subtitle: 'Yamanote Line Station',
        title: 'Shibuya Platform 1 Teichiku',
        url: '/midi/train-stations/shibuya-platform-1-teichiku.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:08',
        fileName: 'shibuya-platform-2.mid',
        id: 'train-stations/shibuya-platform-2',
        subtitle: 'Yamanote Line Station',
        title: 'Shibuya Platform 2',
        url: '/midi/train-stations/shibuya-platform-2.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:04',
        fileName: 'shibuya-yamaha-original.mid',
        id: 'train-stations/shibuya-yamaha-original',
        subtitle: 'Yamanote Line Station',
        title: 'Shibuya Yamaha Original',
        url: '/midi/train-stations/shibuya-yamaha-original.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:27',
        fileName: 'shinagawa.mid',
        id: 'train-stations/shinagawa',
        subtitle: 'Yamanote Line Station',
        title: 'Shinagawa',
        url: '/midi/train-stations/shinagawa.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:13',
        fileName: 'shinbashi-platform-1.mid',
        id: 'train-stations/shinbashi-platform-1',
        subtitle: 'Yamanote Line Station',
        title: 'Shinbashi Platform 1',
        url: '/midi/train-stations/shinbashi-platform-1.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:13',
        fileName: 'shinbashi-platform-2.mid',
        id: 'train-stations/shinbashi-platform-2',
        subtitle: 'Yamanote Line Station',
        title: 'Shinbashi Platform 2',
        url: '/midi/train-stations/shinbashi-platform-2.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:12',
        fileName: 'shinjuku-teichiku-platform-2.mid',
        id: 'train-stations/shinjuku-teichiku-platform-2',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 2',
        url: '/midi/train-stations/shinjuku-teichiku-platform-2.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:09',
        fileName: 'shinjuku-teichiku-platform-3.mid',
        id: 'train-stations/shinjuku-teichiku-platform-3',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 3',
        url: '/midi/train-stations/shinjuku-teichiku-platform-3.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:10',
        fileName: 'shinjuku-teichiku-platform-4.mid',
        id: 'train-stations/shinjuku-teichiku-platform-4',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 4',
        url: '/midi/train-stations/shinjuku-teichiku-platform-4.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:12',
        fileName: 'shinjuku-teichiku-platform-6.mid',
        id: 'train-stations/shinjuku-teichiku-platform-6',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 6',
        url: '/midi/train-stations/shinjuku-teichiku-platform-6.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:09',
        fileName: 'shinjuku-teichiku-platform-7.mid',
        id: 'train-stations/shinjuku-teichiku-platform-7',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 7',
        url: '/midi/train-stations/shinjuku-teichiku-platform-7.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:11',
        fileName: 'shinjuku-teichiku-platform-8.mid',
        id: 'train-stations/shinjuku-teichiku-platform-8',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 8',
        url: '/midi/train-stations/shinjuku-teichiku-platform-8.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:09',
        fileName: 'shinjuku-teichiku-platform-9.mid',
        id: 'train-stations/shinjuku-teichiku-platform-9',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 9',
        url: '/midi/train-stations/shinjuku-teichiku-platform-9.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:12',
        fileName: 'shinjuku-teichiku-platform-10.mid',
        id: 'train-stations/shinjuku-teichiku-platform-10',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 10',
        url: '/midi/train-stations/shinjuku-teichiku-platform-10.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:11',
        fileName: 'shinjuku-teichiku-platform-11.mid',
        id: 'train-stations/shinjuku-teichiku-platform-11',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 11',
        url: '/midi/train-stations/shinjuku-teichiku-platform-11.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:09',
        fileName: 'shinjuku-teichiku-platform-12.mid',
        id: 'train-stations/shinjuku-teichiku-platform-12',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 12',
        url: '/midi/train-stations/shinjuku-teichiku-platform-12.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:10',
        fileName: 'shinjuku-teichiku-platform-14.mid',
        id: 'train-stations/shinjuku-teichiku-platform-14',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Teichiku Platform 14',
        url: '/midi/train-stations/shinjuku-teichiku-platform-14.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:06',
        fileName: 'shinjuku-yamaha-platform-2.mid',
        id: 'train-stations/shinjuku-yamaha-platform-2',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Yamaha Platform 2',
        url: '/midi/train-stations/shinjuku-yamaha-platform-2.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:06',
        fileName: 'shinjuku-yamaha-platform-3.mid',
        id: 'train-stations/shinjuku-yamaha-platform-3',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Yamaha Platform 3',
        url: '/midi/train-stations/shinjuku-yamaha-platform-3.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:05',
        fileName: 'shinjuku-yamaha-platform-4.mid',
        id: 'train-stations/shinjuku-yamaha-platform-4',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Yamaha Platform 4',
        url: '/midi/train-stations/shinjuku-yamaha-platform-4.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:07',
        fileName: 'shinjuku-yamaha-platform-5.mid',
        id: 'train-stations/shinjuku-yamaha-platform-5',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Yamaha Platform 5',
        url: '/midi/train-stations/shinjuku-yamaha-platform-5.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:04',
        fileName: 'shinjuku-yamaha-platform-7.mid',
        id: 'train-stations/shinjuku-yamaha-platform-7',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Yamaha Platform 7',
        url: '/midi/train-stations/shinjuku-yamaha-platform-7.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:07',
        fileName: 'shinjuku-yamaha-platform-12.mid',
        id: 'train-stations/shinjuku-yamaha-platform-12',
        subtitle: 'Yamanote Line Station',
        title: 'Shinjuku Yamaha Platform 12',
        url: '/midi/train-stations/shinjuku-yamaha-platform-12.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:15',
        fileName: 'suidobashi.mid',
        id: 'train-stations/suidobashi',
        subtitle: 'Tokyo Area Station',
        title: 'Suidobashi',
        url: '/midi/train-stations/suidobashi.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:17',
        fileName: 'takadanobaba-astro-boy.mid',
        id: 'train-stations/takadanobaba-astro-boy',
        subtitle: 'Yamanote Line Station',
        title: 'Takadanobaba Astro Boy',
        url: '/midi/train-stations/takadanobaba-astro-boy.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:09',
        fileName: 'tokyo-jr-sh1.mid',
        id: 'train-stations/tokyo-jr-sh1',
        subtitle: 'Yamanote Line Station',
        title: 'Tokyo JR-SH1',
        url: '/midi/train-stations/tokyo-jr-sh1.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:09',
        fileName: 'tokyo-jr-sh3.mid',
        id: 'train-stations/tokyo-jr-sh3',
        subtitle: 'Yamanote Line Station',
        title: 'Tokyo JR-SH3',
        url: '/midi/train-stations/tokyo-jr-sh3.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:08',
        fileName: 'ueno-jr-sh5.mid',
        id: 'train-stations/ueno-jr-sh5',
        subtitle: 'Tokyo Area Station',
        title: 'Ueno JR-SH5',
        url: '/midi/train-stations/ueno-jr-sh5.mid',
      },
      {
        categoryId: 'train-stations',
        categoryLabel: 'Japanese Train Melodies: Stations',
        durationLabel: '0:09',
        fileName: 'yoyogi-platform-4.mid',
        id: 'train-stations/yoyogi-platform-4',
        subtitle: 'Yamanote Line Station',
        title: 'Yoyogi Platform 4',
        url: '/midi/train-stations/yoyogi-platform-4.mid',
      },
    ],
    label: 'Japanese Train Melodies: Stations',
  },
  {
    id: 'train-standard-chimes',
    items: [
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:11',
        fileName: 'jnr-classic-chime.mid',
        id: 'train-standard-chimes/jnr-classic-chime',
        subtitle: 'JR-SH Standard Melody',
        title: 'JNR Classic Chime',
        url: '/midi/train-standard-chimes/jnr-classic-chime.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:08',
        fileName: 'jr-departure-chime.mid',
        id: 'train-standard-chimes/jr-departure-chime',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR Departure Chime',
        url: '/midi/train-standard-chimes/jr-departure-chime.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:02',
        fileName: 'jr-tokyo-east-jingle.mid',
        id: 'train-standard-chimes/jr-tokyo-east-jingle',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR Tokyo East Jingle',
        url: '/midi/train-standard-chimes/jr-tokyo-east-jingle.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:07',
        fileName: 'jr-sf3.mid',
        id: 'train-standard-chimes/jr-sf3',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR-SF3',
        url: '/midi/train-standard-chimes/jr-sf3.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:06',
        fileName: 'jr-sh1.mid',
        id: 'train-standard-chimes/jr-sh1',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR-SH1',
        url: '/midi/train-standard-chimes/jr-sh1.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:07',
        fileName: 'jr-sh2.mid',
        id: 'train-standard-chimes/jr-sh2',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR-SH2',
        url: '/midi/train-standard-chimes/jr-sh2.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:09',
        fileName: 'jr-sh4.mid',
        id: 'train-standard-chimes/jr-sh4',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR-SH4',
        url: '/midi/train-standard-chimes/jr-sh4.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:07',
        fileName: 'jr-sh5.mid',
        id: 'train-standard-chimes/jr-sh5',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR-SH5',
        url: '/midi/train-standard-chimes/jr-sh5.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:08',
        fileName: 'jr-sh6.mid',
        id: 'train-standard-chimes/jr-sh6',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR-SH6',
        url: '/midi/train-standard-chimes/jr-sh6.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:12',
        fileName: 'jr-sh7.mid',
        id: 'train-standard-chimes/jr-sh7',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR-SH7',
        url: '/midi/train-standard-chimes/jr-sh7.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:09',
        fileName: 'jr-sh8.mid',
        id: 'train-standard-chimes/jr-sh8',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR-SH8',
        url: '/midi/train-standard-chimes/jr-sh8.mid',
      },
      {
        categoryId: 'train-standard-chimes',
        categoryLabel: 'Japanese Train Melodies: Standard Chimes',
        durationLabel: '0:09',
        fileName: 'jr-sh9.mid',
        id: 'train-standard-chimes/jr-sh9',
        subtitle: 'JR-SH Standard Melody',
        title: 'JR-SH9',
        url: '/midi/train-standard-chimes/jr-sh9.mid',
      },
    ],
    label: 'Japanese Train Melodies: Standard Chimes',
  },
  {
    id: 'train-signature-system',
    items: [
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:06',
        fileName: 'chigasaki-melody.mid',
        id: 'train-signature-system/chigasaki-melody',
        subtitle: 'Railway Medley / Misc',
        title: 'Chigasaki Melody',
        url: '/midi/train-signature-system/chigasaki-melody.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:13',
        fileName: 'cielo-estrellado.mid',
        id: 'train-signature-system/cielo-estrellado',
        subtitle: 'Named Train Melody',
        title: 'Cielo Estrellado',
        url: '/midi/train-signature-system/cielo-estrellado.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:06',
        fileName: 'classic-sakura-sakura.mid',
        id: 'train-signature-system/classic-sakura-sakura',
        subtitle: 'Named Train Melody',
        title: 'Classic Sakura Sakura',
        url: '/midi/train-signature-system/classic-sakura-sakura.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:08',
        fileName: 'dragonnight-departure-melody.mid',
        id: 'train-signature-system/dragonnight-departure-melody',
        subtitle: 'Railway Medley / Misc',
        title: 'Dragonnight Departure Melody',
        url: '/midi/train-signature-system/dragonnight-departure-melody.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:07',
        fileName: 'fujisawa.mid',
        id: 'train-signature-system/fujisawa',
        subtitle: 'Railway Medley / Misc',
        title: 'Fujisawa',
        url: '/midi/train-signature-system/fujisawa.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:17',
        fileName: 'itteki-one-drop.mid',
        id: 'train-signature-system/itteki-one-drop',
        subtitle: 'Named Train Melody',
        title: 'Itteki One Drop',
        url: '/midi/train-signature-system/itteki-one-drop.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:20',
        fileName: 'keikyu-melody.mid',
        id: 'train-signature-system/keikyu-melody',
        subtitle: 'Metro / Private Railway Melody',
        title: 'Keikyu Melody',
        url: '/midi/train-signature-system/keikyu-melody.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:08',
        fileName: 'keio-melody.mid',
        id: 'train-signature-system/keio-melody',
        subtitle: 'Metro / Private Railway Melody',
        title: 'Keio Melody',
        url: '/midi/train-signature-system/keio-melody.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:08',
        fileName: 'metro-eidan-melody-a.mid',
        id: 'train-signature-system/metro-eidan-melody-a',
        subtitle: 'Metro / Private Railway Melody',
        title: 'Metro Eidan Melody A',
        url: '/midi/train-signature-system/metro-eidan-melody-a.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:09',
        fileName: 'metro-eidan-melody-b.mid',
        id: 'train-signature-system/metro-eidan-melody-b',
        subtitle: 'Metro / Private Railway Melody',
        title: 'Metro Eidan Melody B',
        url: '/midi/train-signature-system/metro-eidan-melody-b.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:06',
        fileName: 'metro-trta-melody-a.mid',
        id: 'train-signature-system/metro-trta-melody-a',
        subtitle: 'Metro / Private Railway Melody',
        title: 'Metro TRTA Melody A',
        url: '/midi/train-signature-system/metro-trta-melody-a.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:10',
        fileName: 'metro-trta-melody-b.mid',
        id: 'train-signature-system/metro-trta-melody-b',
        subtitle: 'Metro / Private Railway Melody',
        title: 'Metro TRTA Melody B',
        url: '/midi/train-signature-system/metro-trta-melody-b.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:07',
        fileName: 'nambu-line-melody.mid',
        id: 'train-signature-system/nambu-line-melody',
        subtitle: 'Railway Medley / Misc',
        title: 'Nambu Line Melody',
        url: '/midi/train-signature-system/nambu-line-melody.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:07',
        fileName: 'narita-airport-melody.mid',
        id: 'train-signature-system/narita-airport-melody',
        subtitle: 'Railway Medley / Misc',
        title: 'Narita Airport Melody',
        url: '/midi/train-signature-system/narita-airport-melody.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:03',
        fileName: 'odakyu-melody.mid',
        id: 'train-signature-system/odakyu-melody',
        subtitle: 'Metro / Private Railway Melody',
        title: 'Odakyu Melody',
        url: '/midi/train-signature-system/odakyu-melody.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:11',
        fileName: 'shinkansen-hikari-chime.mid',
        id: 'train-signature-system/shinkansen-hikari-chime',
        subtitle: 'Shinkansen Chime',
        title: 'Shinkansen Hikari Chime',
        url: '/midi/train-signature-system/shinkansen-hikari-chime.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:10',
        fileName: 'shinkansen-joetsu-chime.mid',
        id: 'train-signature-system/shinkansen-joetsu-chime',
        subtitle: 'Shinkansen Chime',
        title: 'Shinkansen Joetsu Chime',
        url: '/midi/train-signature-system/shinkansen-joetsu-chime.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:09',
        fileName: 'shinkansen-nozomi-chime.mid',
        id: 'train-signature-system/shinkansen-nozomi-chime',
        subtitle: 'Shinkansen Chime',
        title: 'Shinkansen Nozomi Chime',
        url: '/midi/train-signature-system/shinkansen-nozomi-chime.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:10',
        fileName: 'shinkansen-tohoku-chime.mid',
        id: 'train-signature-system/shinkansen-tohoku-chime',
        subtitle: 'Shinkansen Chime',
        title: 'Shinkansen Tohoku Chime',
        url: '/midi/train-signature-system/shinkansen-tohoku-chime.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:21',
        fileName: 'tobu-asakusa.mid',
        id: 'train-signature-system/tobu-asakusa',
        subtitle: 'Metro / Private Railway Melody',
        title: 'Tobu Asakusa',
        url: '/midi/train-signature-system/tobu-asakusa.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:57',
        fileName: 'tobu-ikebukuro.mid',
        id: 'train-signature-system/tobu-ikebukuro',
        subtitle: 'Metro / Private Railway Melody',
        title: 'Tobu Ikebukuro',
        url: '/midi/train-signature-system/tobu-ikebukuro.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:08',
        fileName: 'tokyu-melody.mid',
        id: 'train-signature-system/tokyu-melody',
        subtitle: 'Metro / Private Railway Melody',
        title: 'Tokyu Melody',
        url: '/midi/train-signature-system/tokyu-melody.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:14',
        fileName: 'unipex-haru-spring.mid',
        id: 'train-signature-system/unipex-haru-spring',
        subtitle: 'Named Train Melody',
        title: 'Unipex Haru Spring',
        url: '/midi/train-signature-system/unipex-haru-spring.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:17',
        fileName: 'unipex-kokoro-heart.mid',
        id: 'train-signature-system/unipex-kokoro-heart',
        subtitle: 'Named Train Melody',
        title: 'Unipex Kokoro Heart',
        url: '/midi/train-signature-system/unipex-kokoro-heart.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:19',
        fileName: 'unipex-seiryu-clear-stream.mid',
        id: 'train-signature-system/unipex-seiryu-clear-stream',
        subtitle: 'Named Train Melody',
        title: 'Unipex Seiryu Clear Stream',
        url: '/midi/train-signature-system/unipex-seiryu-clear-stream.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:13',
        fileName: 'unipex-seseragi.mid',
        id: 'train-signature-system/unipex-seseragi',
        subtitle: 'Named Train Melody',
        title: 'Unipex Seseragi',
        url: '/midi/train-signature-system/unipex-seseragi.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:19',
        fileName: 'unipex-shiki-four-seasons.mid',
        id: 'train-signature-system/unipex-shiki-four-seasons',
        subtitle: 'Named Train Melody',
        title: 'Unipex Shiki Four Seasons',
        url: '/midi/train-signature-system/unipex-shiki-four-seasons.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:23',
        fileName: 'verde-green.mid',
        id: 'train-signature-system/verde-green',
        subtitle: 'Named Train Melody',
        title: 'Verde Green',
        url: '/midi/train-signature-system/verde-green.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:11',
        fileName: 'water-crown.mid',
        id: 'train-signature-system/water-crown',
        subtitle: 'Named Train Melody',
        title: 'Water Crown',
        url: '/midi/train-signature-system/water-crown.mid',
      },
      {
        categoryId: 'train-signature-system',
        categoryLabel: 'Japanese Train Melodies: Signature, Rail & Medleys',
        durationLabel: '0:07',
        fileName: 'yamanote-new-jre-ikst-melody.mid',
        id: 'train-signature-system/yamanote-new-jre-ikst-melody',
        subtitle: 'Railway Medley / Misc',
        title: 'Yamanote New JRE-IKST Melody',
        url: '/midi/train-signature-system/yamanote-new-jre-ikst-melody.mid',
      },
    ],
    label: 'Japanese Train Melodies: Signature, Rail & Medleys',
  },
]

export const MIDI_LIBRARY: MidiLibraryItem[] = MIDI_LIBRARY_CATEGORIES.flatMap(
  category => category.items,
)

export const DEFAULT_LIBRARY_TRACK: MidiLibraryItem | undefined
  = MIDI_LIBRARY.find(item => item.id === 'originals/miras-theme')
